# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    # docker:
    # specify the version you desire here
    #  - image: lalithsuresh/dcm-ci-latest
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/dcm

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run: apt-get update && apt install -y wget maven libglu1 && \
             wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.3.2/MiniZincIDE-2.3.2-bundle-linux-x86_64.tgz && \
             mv MiniZincIDE-2.3.2-bundle-linux-x86_64.tgz /minizinc.tgz && \
             cd / && \
             tar -xzvf /minizinc.tgz && \
             mv /MiniZincIDE-2.3.2-bundle-linux /minizinc && \
             rm /minizinc.tgz

      - checkout

      # run tests!
      - run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package 
      - run: mvn -pl '!build-common' jacoco:report
      - run: bash <(curl -s https://codecov.io/bash)

      # collect test metadata
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit 
